[package]

name = "websocket-reuseaddr"
version = "0.18.1"
authors = ["cyderize <admin@cyderize.org>", "Vitaly \"_Vi\" Shukela <vi0oss@gmail.com>", "Alexey Gerasev <alexey.gerasev@gmail.com>"]

description = "A WebSocket (RFC6455) library for Rust (fork)."

documentation = "http://cyderize.github.io/rust-websocket/doc/websocket/"
homepage = "http://cyderize.github.io/rust-websocket/"
repository = "https://github.com/nthend/rust-websocket.git"

readme = "README.md"

keywords = ["websocket", "websockets", "rfc6455"]

license = "MIT"

[dependencies]
hyper = { version = ">=0.7, <0.10", default-features=false }
unicase = "1.0.1"
openssl = { version = "0.7.6", optional=true }
url = "1.0"
rustc-serialize = "0.3.16"
bitflags = "0.7"
rand = "0.3.12"
byteorder = "0.5.1"
net2 = "0.2.17"
sha1 = "0.2.0"

[features]
default = ["ssl", "reuseaddr"]
nightly = ["hyper/nightly"]
ssl = ["openssl", "hyper/ssl"]
reuseaddr = []